### ISSUE TITLE
iOS 13 support for BackgrounderAction for CCSupport?

### ISSUE THREAD

**Issue by sebj54** [akusio/akusio.github.io#3]
Hi there, 

Just tested BackgrounderAction for CCSupport on an iPad (iPadOS 13.1) and it does nothing.

Do you plan to update this tweak? 

Thanks!

**Comment by limuzioper** [comment]
i funde the lastest version has supported iPadOS 13.3,you may try it

**Comment by sebj54** [comment]
You're right. It is a new package though: BackgrounderAction2 for CCSupport
